greeting:
  image: my/greeting
  replicaCount: 1

image:
  imagePullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080
  externalDebugPort: 5005
  internalDebugPort: 5005
